Produce an index error for out of bound accesses
This was previously producing the following error, which was much harder
to interpret what was wrong:

```python
ValueError: cannot select an axis to squeeze out which has size not equal to one
```

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>