Add missing template instantiation
The lack of this was causing import errors in python, such as:

>>> from stempy import io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/virtualenvs/python3.8-test/lib/python3.8/site-packages/stempy/io/__init__.py", line 5, in <module>
    from stempy._io import (
ImportError: /home/patrick/virtualenvs/python3.8-test/lib/python3.8/site-packages/stempy/libstem.so: undefined symbol: _ZN6stempy19calculateThresholdsINS_5BlockEtLb1EEENS_26CalculateThresholdsResultsIT0_EERSt6vectorIT_SaIS6_EEPKfiddSB_
>>> from stempy import image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/virtualenvs/python3.8-test/lib/python3.8/site-packages/stempy/image/__init__.py", line 1, in <module>
    from stempy import _image
ImportError: /home/patrick/virtualenvs/python3.8-test/lib/python3.8/site-packages/stempy/libstem.so: undefined symbol: _ZN6stempy19calculateThresholdsINS_5BlockEtLb1EEENS_26CalculateThresholdsResultsIT0_EERSt6vectorIT_SaIS6_EEPKfiddSB_

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>